name = "CalcephEphemeris"
uuid = "54e8752a-b65a-4aac-bda5-4918ee1e3cc5"
authors = ["JSMD Team"]
version = "1.2.0"

[deps]
CALCEPH_jll = "dd3044d3-6c85-52eb-b239-9fbeaa51d7ac"
JSMDInterfaces = "6b30ee2f-618e-4a15-bf4e-7df7b496e609"

[compat]
CALCEPH_jll = "3.5"
julia = "1.6"
JSMDInterfaces = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
