name = "CalcephEphemeris"
uuid = "54e8752a-b65a-4aac-bda5-4918ee1e3cc5"
authors = ["Andrea Pasquale <andrea.pasquale@polimi.it> and Michele Ceresoli <michele.ceresoli@polimi.it>"]
version = "1.1.3"

[deps]
CALCEPH = "1537fe66-4725-5aba-80f4-3a74792cecc1"
JSMDInterfaces = "6b30ee2f-618e-4a15-bf4e-7df7b496e609"

[compat]
CALCEPH = "1.1"
julia = "1"
JSMDInterfaces = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
