name = "CalcephEphemeris"
uuid = "54e8752a-b65a-4aac-bda5-4918ee1e3cc5"
authors = ["Andrea Pasquale <andrea.pasquale@polimi.it> and Michele Ceresoli <michele.ceresoli@polimi.it>"]
version = "1.0.0"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]